### ISSUE TITLE
Failure to run kobas-i (docker)

### ISSUE THREAD

**Issue by SantosRAC** [fionamcc/Docs#7]
Dear @suryasaha,

I am having problems to run the docker container for KOBAS-i on Docker version 20.10.24, build 297e128 (on Ubuntu 22).

This command-line seems to work:

```bash
sudo docker pull agbase/kobas:3.0.3_3
```

However, the next command returns an error related a folder ("seq_pep/"), when I run:

```
sudo docker run --rm -v $(pwd):/work-dir agbase/kobas:3.0.3_3 -h
```

![image](https://github.com/fionamcc/Docs/assets/7959954/97d255d9-0513-4fa6-90a5-c5702eb1a861)

And such error seems to be related to the unavailability of download files (?):

![image](https://github.com/fionamcc/Docs/assets/7959954/71312e07-6037-4993-88d2-8d27ee4be950)

Could you help us ?

Thanks a lot,
Renato Santos.

**Comment by amcooksey** [comment]
@SantosRAC Thanks for letting us know about the error. It should be fixed now if you want to pull the image again from DockerHub. 
We are working to update the documentation to reflect changes to the new image but they are currently out of date. As of version 3.0.3_3, you should no longer have to download the files manually before you run the tool. Also, you will no longer have to mount those directories at run time. 
You can run the tool like so: 
sudo docker run \
--rm \
-v $(pwd):/work-dir \
agbase/kobas:3.0.3_3 \
-a \
-i AROS1000.fa \
-s dme \
-t fasta:pro \
-o AROS1000

**Comment by SantosRAC** [comment]
Dear @amcooksey , thanks a lot for your response.

It is now running - I will let you know if it really works!

In the current docker version, `agbase/kobas:3.0.3_3 -h` shows links to `cbi.pku.edu.cn` and `kegg.jp`. However, species in kegg are not necessarily available in the Chinese server.

It would be nice to fix it too, or ensure all species are available in both servers.

Cheers,
Renato Santos.
